[package]
name = "syt-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }

reqwest = "0.12"
clap = { version = "4.5", features = ["derive"] }
